### ISSUE TITLE
Verify NSNumber, CIColor and CIVector filters

### ISSUE THREAD

**Issue by nikolaydymura** [nikolaydymura/flutter_core_image_filters#55]
- [x] Area Average			`CIAreaAverage`
- [x] Area Histogram			`CIAreaHistogram`
- [x] Area Logarithmic Histogram			`CIAreaLogarithmicHistogram`
- [x] Area Maximum			`CIAreaMaximum`
- [x] Area Maximum Alpha			`CIAreaMaximumAlpha`
- [x] Area Minimum			`CIAreaMinimum`
- [x] Area Minimum Alpha			`CIAreaMinimumAlpha`
- [x] Area Min and Max			`CIAreaMinMax`
- [x] Area Min and Max Red			`CIAreaMinMaxRed`
- [x] Bump Distortion			`CIBumpDistortion`
- [x] Bump Distortion Linear			`CIBumpDistortionLinear`
- [ ] Checkerboard			`CICheckerboardGenerator`
- [x] Circle Splash Distortion			`CICircleSplashDistortion`
- [x] Circular Screen			`CICircularScreen`
- [x] Circular Wrap Distortion			`CICircularWrap`
- [x] Clamp			`CIClamp`
- [x] CMYK Halftone			`CICMYKHalftone`
- [x] Color Clamp			`CIColorClamp`
- [x] Color Cross Polynomial			`CIColorCrossPolynomial`
- [x] Color Matrix			`CIColorMatrix`
- [x] Color Polynomial			`CIColorPolynomial`
- [x] Column Average			`CIColumnAverage`
- [x] 3 by 3 Convolution			`CIConvolution3X3`
- [x] 5 by 5 Convolution			`CIConvolution5X5`
- [x] 7 by 7 Convolution			`CIConvolution7X7`
- [x] Horizontal 9 Convolution			`CIConvolution9Horizontal`
- [x] Vertical 9 Convolution			`CIConvolution9Vertical`
- [x] 3 by 3 RGB Convolution			`CIConvolutionRGB3X3`
- [x] 5 by 5 RGB Convolution			`CIConvolutionRGB5X5`
- [x] 7 by 7 RGB Convolution			`CIConvolutionRGB7X7`
- [x] Horizontal 9 RGB Convolution			`CIConvolutionRGB9Horizontal`
- [x] Vertical 9 RGB Convolution			`CIConvolutionRGB9Vertical`
- [x] Crop			`CICrop`
- [x] Crystallize			`CICrystallize`
- [x] Depth of Field			`CIDepthOfField`
- [x] Dot Screen			`CIDotScreen`
- [x] Droste			`CIDroste`
- [x] Eightfold Reflected Tile			`CIEightfoldReflectedTile`
- [x] Fourfold Reflected Tile			`CIFourfoldReflectedTile`
- [x] Fourfold Rotated Tile			`CIFourfoldRotatedTile`
- [x] Fourfold Translated Tile			`CIFourfoldTranslatedTile`
- [x] Gaussian Gradient			`CIGaussianGradient`
- [x] Glass Lozenge			`CIGlassLozenge`
- [x] Glide Reflected Tile			`CIGlideReflectedTile`
- [x] Hatched Screen			`CIHatchedScreen`
- [x] Hexagonal Pixelate			`CIHexagonalPixellate`
- [x] Hole Distortion			`CIHoleDistortion`
- [x] Kaleidoscope			`CIKaleidoscope`
- [x] Combined Keystone Correction			`CIKeystoneCorrectionCombined`
- [x] Horizontal Keystone Correction			`CIKeystoneCorrectionHorizontal`
- [x] Vertical Keystone Correction			`CIKeystoneCorrectionVertical`
- [x] Lenticular Halo			`CILenticularHaloGenerator`
- [x] Light Tunnel Distortion			`CILightTunnel`
- [x] Linear Gradient			`CILinearGradient`
- [x] Line Screen			`CILineScreen`
- [x] Nine Part Stretched			`CINinePartStretched`
- [x] Nine Part Tiled			`CINinePartTiled`
- [x] Op Tile			`CIOpTile`
- [x] Parallelogram Tile			`CIParallelogramTile`
- [x] Perspective Correction			`CIPerspectiveCorrection`
- [x] Perspective Tile			`CIPerspectiveTile`
- [x] Perspective Transform			`CIPerspectiveTransform`
- [x] Perspective Transform with Extent			`CIPerspectiveTransformWithExtent`
- [x] Pinch Distortion			`CIPinchDistortion`
- [x] Pixelate			`CIPixellate`
- [x] Pointillize			`CIPointillize`
- [x] Radial Gradient			`CIRadialGradient`
- [x] Rounded Rectangle Generator			`CIRoundedRectangleGenerator`
- [x] Row Average			`CIRowAverage`
- [x] Sixfold Reflected Tile			`CISixfoldReflectedTile`
- [x] Sixfold Rotated Tile			`CISixfoldRotatedTile`
- [x] Smooth Linear Gradient			`CISmoothLinearGradient`
- [x] Spot Light			`CISpotLight`
- [x] Star Shine			`CIStarShineGenerator`
- [x] Stretch Crop			`CIStretchCrop`
- [x] Stripes			`CIStripesGenerator`
- [x] Sunbeams			`CISunbeamsGenerator`
- [x] Temperature and Tint			`CITemperatureAndTint`
- [x] Tone Curve			`CIToneCurve`
- [x] Torus Lens Distortion			`CITorusLensDistortion`
- [x] Triangle Kaleidoscope			`CITriangleKaleidoscope`
- [x] Triangle Tile			`CITriangleTile`
- [x] Twelvefold Reflected Tile			`CITwelvefoldReflectedTile`
- [x] Twirl Distortion			`CITwirlDistortion`
- [x] Vignette Effect			`CIVignetteEffect`
- [x] Vortex Distortion			`CIVortexDistortion`
- [x] Zoom Blur			`CIZoomBlur`

**Comment by nikolaydymura** [comment]
`Rect.fromLTWH(0, 0, 640, 480);` ----> `CIVector(cgRect: CGRect(x: 0, y: 0, width: 640, height: 480))`
`Point( 640, 480);` ----> `CIVector(cgPoint: CGPoint(x: 640, y: 480))`
`[1, 2, 3, 4, 5, 6]` ----> `CIVector(values: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0], count: 7)`

**Comment by nataliiazabiiaka** [comment]
Area Average CIAreaAverage,  Area Histogram CIAreaHistogram, Area Logarithmic Histogram CIAreaLogarithmicHistogram,  Area Maximum CIAreaMaximum, Area Maximum Alpha CIAreaMaximumAlpha, Area Minimum CIAreaMinimum, Area Minimum Alpha CIAreaMinimumAlpha, Area Min and Max CIAreaMinMax, Area Min and Max Red CIAreaMinMaxRed, Column Average CIColumnAverage, Row Average CIRowAverage - this screens has two small pink screens instead of photos - on bottom and top screen, and nothing on the center screen;
Area Logarithmic Histogram CIAreaLogarithmicHistogram - can't enter _scale parameter;
Clamp CIClamp - blurry turquoise screens instead of photos;
Color Clamp CIColorClamp, 3 by 3 Convolution CIConvolution3X3 - too light;
Circular Wrap Distortion CICircularWrap - too big radius and pink fone;
Circle Splash Distortion CICircleSplashDistortion, Checkerboard CICheckerboardGenerator, Bump Distortion CIBumpDistortion, Droste CIDroste, Eightfold Reflected Tile CIEightfoldReflectedTile,  Fourfold Reflected Tile CIFourfoldReflectedTile,  Fourfold Rotated Tile CIFourfoldRotatedTile, Fourfold Translated Tile CIFourfoldTranslatedTile, Gaussian Gradient CIGaussianGradient,  Glide Reflected Tile CIGlideReflectedTile, Light Tunnel Distortion CILightTunnel, Linear Gradient CILinearGradient, Op Tile CIOpTile, Parallelogram Tile CIParallelogramTile, Perspective Tile CIPerspectiveTile, Radial Gradient CIRadialGradient, Rounded Rectangle Generator CIRoundedRectangleGenerator, Sixfold Reflected Tile CISixfoldReflectedTile, Sixfold Rotated Tile CISixfoldRotatedTile, Smooth Linear Gradient CISmoothLinearGradient, Spot Light CISpotLight, Star Shine CIStarShineGenerator, Stripes CIStripesGenerator, Sunbeams CISunbeamsGenerator, Triangle Kaleidoscope CITriangleKaleidoscope, Triangle Tile CITriangleTile, Twelvefold Reflected Tile CITwelvefoldReflectedTile, Zoom Blur CIZoomBlur - can't open this filters in Xcode (but majority open in flutter simulator (nothing to compare));
Color Cross Polynomial CIColorCrossPolynomial, Color Matrix CIColorMatrix, Color Polynomial CIColorPolynomial, Lenticular Halo CILenticularHaloGenerator - only standard values, do not work for other preset values;
5 by 5 RGB Convolution CIConvolutionRGB5X5 - can't open this filter in flutter simulator;
Horizontal 9 RGB Convolution CIConvolutionRGB9Horizontal, 7 by 7 RGB Convolution CIConvolutionRGB7X7, 3 by 3 Convolution CIConvolution3X3, Vertical 9 RGB Convolution CIConvolutionRGB9Vertical -  when you change _bias parameter - white screens;
Glass Lozenge CIGlassLozenge, Hole Distortion CIHoleDistortion, Kaleidoscope CIKaleidoscope, Perspective Correction CIPerspectiveCorrection, Perspective Transform CIPerspectiveTransform, Perspective Transform with Extent CIPerspectiveTransformWithExtent, Pinch Distortion CIPinchDistortion, Stretch Crop CIStretchCrop - very big different;
Combined Keystone Correction CIKeystoneCorrectionCombined,  Vertical Keystone Correction CIKeystoneCorrectionVertical - yes, but this screens has pink fone on bottom and top screen;
Twirl Distortion CITwirlDistortion - too big radius

**Comment by nataliiazabiiaka** [comment]
Area Average CIAreaAverage, Area Histogram CIAreaHistogram,  Area Logarithmic Histogram CIAreaLogarithmicHistogram, Area Maximum CIAreaMaximum, Area Minimum Alpha CIAreaMinimumAlpha, Area Min and Max CIAreaMinMax,  Area Min and Max Red CIAreaMinMaxRed, Column Average CIColumnAverage, Row Average CIRowAverage - don't working, this screens has only two small pink screens instead of photos - on bottom and top screen, and nothing on the center screen;

Area Logarithmic Histogram CIAreaLogarithmicHistogram - working in flutter, but can't enter _scale parameter;

Checkerboard CICheckerboardGenerator, Gaussian Gradient CIGaussianGradient, Lenticular Halo CILenticularHaloGenerator (this filter working with only constant values), Radial Gradient CIRadialGradient, Rounded Rectangle Generator CIRoundedRectangleGenerator, Smooth Linear Gradient CISmoothLinearGradient, Star Shine CIStarShineGenerator, Stripes CIStripesGenerator, Sunbeams CISunbeamsGenerator - working in flutter, but error in Xcode(Thread 1: "[<CICheckerboardGenerator 0x600000b40800> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key inputImage.");

Circular Wrap Distortion CICircularWrap, Color Matrix CIColorMatrix, Glass Lozenge CIGlassLozenge, Hole Distortion CIHoleDistortion, Kaleidoscope CIKaleidoscope, Perspective Transform CIPerspectiveTransform, Perspective Transform with Extent CIPerspectiveTransformWithExtent, Pinch Distortion CIPinchDistortion, Twirl Distortion CITwirlDistortion - working in flutter, but very big different;

Clamp CIClamp - only blue screen;

Color Clamp CIColorClamp - yes, but you can't enter another _minComponents parameter (in Xcode too);
3 by 3 Convolution CIConvolution3X3 , 5 by 5 RGB Convolution CIConvolutionRGB5X5 , 7 by 7 RGB Convolution CIConvolutionRGB7X7, Horizontal 9 Convolution CIConvolution9Horizontal, Vertical 9 RGB Convolution CIConvolutionRGB9Vertical - working in flutter, but you can't center another _bias parameter (in Xcode too);

Color Polynomial CIColorPolynomial - working in flutter, but needs more saturation;

Droste CIDroste, Eightfold Reflected Tile CIEightfoldReflectedTile, Fourfold Reflected Tile CIFourfoldReflectedTile, Fourfold Rotated Tile CIFourfoldRotatedTile, Fourfold Translated Tile CIFourfoldTranslatedTile, Glide Reflected Tile CIGlideReflectedTile, Light Tunnel Distortion CILightTunnel, Linear Gradient CILinearGradient, Op Tile CIOpTile, Parallelogram Tile CIParallelogramTile, Perspective Tile CIPerspectiveTile, Sixfold Reflected Tile CISixfoldReflectedTile, Sixfold Rotated Tile CISixfoldRotatedTile, Triangle Kaleidoscope CITriangleKaleidoscope, Triangle Tile CITriangleTile, Twelvefold Reflected Tile CITwelvefoldReflectedTile - working in flutter, but can't open i Xcode for comparison;

Vertical Keystone Correction CIKeystoneCorrectionVertical, Combined Keystone Correction CIKeystoneCorrectionCombined, Perspective Correction CIPerspectiveCorrection, Perspective Transform with Extent CIPerspectiveTransformWithExtent, Rounded Rectangle Generator CIRoundedRectangleGenerator, Stretch Crop CIStretchCrop - working in flutter, but modified photos are located on the background of pink screens, there are pink backgrounds at the top and bottom of the screen, they are absent in the center;

Gaussian Gradient CIGaussianGradient - don't working (only white screen)

**Comment by nataliiazabiiaka** [comment]
<table><tr><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td></tr><tr><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td></tr><tr><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td></tr><tr><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td></tr></table>

**Comment by nataliiazabiiaka** [comment]
<table><tr><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td></tr><tr><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td></tr><tr><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td></tr><tr><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td><td class="border_l border_r border_t border_b selected"><div class="wrap"><div style="margin: 10px 5px;"></div></div></td></tr></table>
